teams:
- name: firefly-admins
  maintainers:
  - EnriqueL8
- name: staff
  maintainers:
  - ryjones
  members:
  - jwagantall
  - thelinuxfoundation
repositories:
- name: governance
  teams:
    staff: maintain
    firefly-admins: maintain
  visibility: public
